name: chall2026-pixcavation

services:
  pixcavation:
    image: athack-ctf/chall2026-pixcavation:latest
    container_name: chall2026-pixcavation
    build:
      context: .
      dockerfile: source/Dockerfile
    ports:
      - "53019:2026"